### ISSUE TITLE
OAuth Support

### ISSUE THREAD

**Issue by sosedoff** [sosedoff/docker-router#23]
There should be a way to enforce oauth for a domain. This could be accomplished by either having a docker-router.yml (or json) config file or pulling the oauth credentials/configs from the containers themselves. Maybe use something like https://github.com/pusher/oauth2_proxy under the hood. 

For the config file this could look like:

```yaml
oauth:
  # enforce on all paths with google
  my_app_id:
    provider: google
    client_id: STRING
    client_secret: STRING
    google_orgs: ...
    google_emails: ...   
  
  # enforce on specific paths with github
  my_other_app:
    provider: github
    path: /admin
    client_id: STRING
    client_secret: STRING
    github_org: ...
    github_team: ...
```

Then when starting the container add the following labels:

```
docker run -l router.oauth=my_app_id
```

To reload the configuration file we could use a SIGHUP, watching file for changes is not necessary and could result in errors.
